### ISSUE TITLE
Permission nodes don't work

### ISSUE THREAD

**Issue by Lachney** [DeltaWhy/bukkit-invitation-only#2]
Hey sorry for making an issue for a project that hasn't been touched in 2 years but I really need a plugin like this on my server. I am running on Minecraf 1.8.9, plugin is still working wonderfully however just the permission nodes do not work for other people without OP.

https://i.xjon.me/8af.png

**Comment by Phoenix616** [comment]
Are you sure that the player is a member? It [looks like](https://github.com/DeltaWhy/bukkit-invitation-only/blob/master/src/main/java/com/github/deltawhy/invitationonly/InvitationOnly.java#L31) that error message is send when the player isn't one, the actual permission error should also be another (white) error message. Try approving the player to a full member with `/approveinvite <playername>`.

**Comment by Lachney** [comment]
Ahh yes that command actually fixed my issue, the error was misleading apologies for that!
